# Generated by Django 4.2.16 on 2024-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'MEDIUM'), (2, 'High')], default=1),
        ),
    ]
