# Generated by Django 4.2.16 on 2024-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default='1'),
        ),
    ]
