# Generated by Django 4.2.16 on 2024-12-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[('L', 'Low'), ('M', 'Medium'), ('F', 'High')], default='M'),
        ),
    ]
