# Generated by Django 4.2.16 on 2024-12-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.IntegerField(choices=[(1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH')], default=2),
        ),
    ]
